name: Build and Deploy Java App to Azure Web App

on:
  push:
    branches:
      - main  # Change this to your deployment branch if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build with Maven
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: copilottrainingapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar                        # Use target/*.war if your project builds a WAR file
